configuration:
  - node8
  - node9
  - node10

cache:
  - node_modules -> yarn.lock
  - '%LocalAppData%\Yarn\cache -> yarn.lock'

for:
  -
    matrix:
      only:
        - configuration: node8
    branches:
      only:
      - master
    init:
      - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    install:
      - ps: Update-NodeJsInstallation 8.9.0 x64
      - node --version
      - yarn --version
      - yarn install --non-interactive --cache-folder ~/.cache/yarn --ignore-engines
      - yarn run build:e2e
    test_script:
      - yarn run test-ci-windows-8
      - yarn run e2e-ci-windows-8
    # Don't actually build.
    build: off
  -
    matrix:
      only:
        - configuration: node9
    branches:
      only:
      - master
    init:
      - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    install:
      - ps: Update-NodeJsInstallation 9.11.2 x64
      - node --version
      - yarn --version
      - yarn install --non-interactive --cache-folder ~/.cache/yarn --ignore-engines
      - yarn run build:e2e
    test_script:
      - yarn run test-ci-windows-9
      - yarn run e2e-ci-windows-9
    # Don't actually build.
    build: off
  -
    matrix:
      only:
        - configuration: node10
    branches:
      only:
      - master
    init:
      - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    install:
      - ps: Update-NodeJsInstallation 10.13.0 x64
      - node --version
      - yarn --version
      - yarn install --non-interactive --cache-folder ~/.cache/yarn --ignore-engines
      - yarn run build:e2e
    test_script:
      - yarn run test-ci
      - yarn run e2e-ci
    # Don't actually build.
    build: off
