configuration:
  - node8
  - node9
  - node10

for:
  -
    matrix:
      only:
        - configuration: node8
    branches:
      only:
      - master
    init:
      - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    install:
      - ps: Update-NodeJsInstallation 8.9.0 x64
      - node --version
      - yarn --version
      - git clone https://github.com/neo-one-suite/neo-one-playground.git packages\neo-one-playground
      - yarn install --non-interactive
      - yarn run build
    test_script:
      - yarn run test-ci-windows-8
      - yarn run e2e-ci-windows-8
    # Don't actually build.
    build: off
  -
    matrix:
      only:
        - configuration: node9
    branches:
      only:
      - master
    init:
      - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    install:
      - ps: Update-NodeJsInstallation 9.11.2 x64
      - node --version
      - yarn --version
      - git clone https://github.com/neo-one-suite/neo-one-playground.git packages\neo-one-playground
      - yarn install --non-interactive
      - yarn run build
    test_script:
      - yarn run test-ci-windows-9
      - yarn run e2e-ci-windows-9
    # Don't actually build.
    build: off
  -
    matrix:
      only:
        - configuration: node10
    branches:
      only:
      - master
    init:
      - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    install:
      - ps: Update-NodeJsInstallation 10.10.0 x64
      - node --version
      - yarn --version
      - git clone https://github.com/neo-one-suite/neo-one-playground.git packages\neo-one-playground
      - yarn install --non-interactive
      - yarn run build
    test_script:
      - yarn run test-ci
      - yarn run e2e-ci
    # Don't actually build.
    build: off
